# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('case_number', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('block', models.CharField(max_length=50)),
                ('iucr', models.CharField(max_length=4)),
                ('primary_type', models.CharField(max_length=50)),
                ('crime_description', models.CharField(max_length=100)),
                ('location_description', models.CharField(max_length=100)),
                ('has_arrested', models.BooleanField()),
                ('is_domestic', models.BooleanField()),
                ('beat', models.CharField(max_length=4)),
                ('district', models.CharField(max_length=3)),
                ('ward', models.IntegerField(null=True)),
                ('community_area', models.CharField(blank=True, max_length=2)),
                ('fbi_code', models.CharField(max_length=3)),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('year', models.IntegerField()),
                ('updated_on', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
