# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crime', '0002_crime_location'),
        ('map', '0002_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crime.Crime')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='map.Grid')),
            ],
            bases=('crime.crime',),
        ),
    ]
