# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_grid'),
        ('crimemodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='grid',
        ),
        migrations.AddField(
            model_name='crime',
            name='grid',
            field=models.ManyToManyField(related_name='crimes', to='map.Grid'),
        ),
    ]
