# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 11:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('size', models.PositiveIntegerField(default=1000)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='map.CityBorder')),
            ],
        ),
    ]
