# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeprediction', '0004_auto_20160429_0717'),
        ('map', '0002_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='city',
        ),
        migrations.DeleteModel(
            name='Grid',
        ),
    ]
