# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crime', '0003_rename_crime_model_to_criminal_record'),
        ('map', '0002_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='crime.CriminalRecord')),
                ('grid', models.ManyToManyField(related_name='grids', to='map.Grid')),
            ],
        ),
    ]
