# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeprediction', '0003_auto_20160406_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimesample',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='crimesample',
            name='grids',
        ),
        migrations.DeleteModel(
            name='CrimeSample',
        ),
    ]
